---
roles:
  basic_large:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024]
    synced_folders:
      - host_path:  'puppet'
        guest_path: '/root/puppet'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts

  basic_regular:
    private_networks:
      - ip: '0.0.0.0'
        auto_network: true
    synced_folders:
      - host_path:  'puppet'
        guest_path: '/root/puppet'
    provisioners:
      - type: shell
        inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"
      - type: hosts

  basic_windows:
    guest: windows
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
