fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    pe_accounts: "git@github.com:puppetlabs/puppetlabs-pe_accounts.git"
    java_ks: "git://github.com/puppetlabs/puppetlabs-java_ks.git"
  symlinks:
    pe_mcollective: "#{source_dir}"
