require 'puppetlabs_spec_helper/rake_tasks'

# This will allow testing with pe-gem installed rspec and rspec-puppet using
# `/opt/puppet/bin/rake spec`
ENV["PATH"] = "/opt/puppet/bin:#{ENV['PATH']}"

task :default => [:build]

def update_module_version
  gitdesc = %x{git describe}.chomp
  semver = gitdesc.gsub(/v?(\d+\.\d+\.\d+)-?(.*)/) do
    newver = "#{$1}"
    newver << "git-#{$2}" unless $2.empty?
    newver
  end
  modulefile = File.read("Modulefile")
  modulefile.gsub!(/^\s*version\s+'.*?'/, "version '#{semver}'")
  File.open("Modulefile", 'w') do |f|
    f.write(modulefile)
  end
  semver
end

desc "Build Puppet Module Package"
task :build do
  system("gimli README*.markdown")
  FileUtils.cp "Modulefile", "Modulefile.bak"
  update_module_version
  system("puppet-module build")
  FileUtils.mv "Modulefile.bak", "Modulefile"
end
